language: node_js
node_js:
- '6'

script:
  - yarn test

before_deploy:
  - yarn global add auto-dist-tag
  - auto-dist-tag --write

deploy:
  skip_cleanup: true
  provider: npm
  email: tobias.bieniek@gmx.de
  api_key:
    secure: osDlkOWAcum6ZqhoTaOHyFtlEWFeBIuAxmtN26WGmAGuUQ16J1tYI91MrsPaMxbvOUT2hMJOythfudkKqqjriUxNhnfgR2XONYa/wSDb5ChJhB+EFOxc5NHpr3OVjzAobDB0SoE+lH6BGeJU9rSKT2Wuq6jMB66Oi6KGGvzoyKMiKjIfYR1RgFOh/e6ba89KNnCT2u6o/RiBhCrc+rVUZNGiCNa88qKuGjdcLL5eLtjlfJqOtdSP4RjSzlRYcTlNbnTOkJfvp4GXDqLtlc8TQi/ZzLhTWwDu0QFID6tHeumdX6aag6284O+E/TmjmjJsLeT37yet05GuIh9d4rxqz7NXeZtFvBPjmtn8cQjug8F3diMLc+KbTRfSmClgOhxtumwmYYRV4eX3NQGg4yyQ6L9n5AXm3xIi8tWyxGoNvPliw4LuV6wYT4AXD2iZIDdIzgKexG7E5cE6iorNNdnJJYqiEYYC4hHIrRu0wxMpzuKS4BP1KCsUsY9lOabruv9rHDDUoa9b+cUcvcASJCcgiudYGn4zd4CJJPRL6FWyyoqawJxpwPtrZbAowmnLTtFPDXjnpBij2T0fokzGYaUEo6iiuCjfJxE03zKRuf7OMb6Y/KplGC7M3Xum4xaPBbkf5Ain1kPEcy7/uSkpKB5ceCIh4nVWcoLdhRphhYFedmg=
  on:
    tags: true
    repo: Turbo87/flight-recorder-manufacturers
